name = "Mastermind"
uuid = "64e523fd-0d46-4f35-998a-b9c0d6ffdbaf"
authors = ["Daan Van Hauwwermeiren"]
version = "0.2.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
